"""v3

Revision ID: 527a4088bb9a
Revises: f0a8c2125c67
Create Date: 2026-03-05 01:35:28.331815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527a4088bb9a'
down_revision: Union[str, Sequence[str], None] = 'f0a8c2125c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposicoesAutores', 'nomeAutor',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposicoesAutores', 'nomeAutor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
