"""v5

Revision ID: 62bf67825959
Revises: 575bad8ed88a
Create Date: 2026-03-05 14:43:12.921290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bf67825959'
down_revision: Union[str, Sequence[str], None] = '575bad8ed88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deputados', sa.Column('slug', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_deputados_slug'), 'deputados', ['slug'], unique=True)
    op.alter_column('licitacoesItens', 'naturezaDespesa',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('licitacoesItens', 'programaTrabalho',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('licitacoesItens', 'programaTrabalho',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('licitacoesItens', 'naturezaDespesa',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_deputados_slug'), table_name='deputados')
    op.drop_column('deputados', 'slug')
    # ### end Alembic commands ###
