"""v4

Revision ID: 6d5ae5d614c6
Revises: 527a4088bb9a
Create Date: 2026-03-05 01:36:23.441283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5ae5d614c6'
down_revision: Union[str, Sequence[str], None] = '527a4088bb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesas', sa.Column('numSubCota', sa.Integer(), nullable=True))
    op.add_column('despesas', sa.Column('numEspecificacaoSubCota', sa.Integer(), nullable=True))
    op.add_column('despesas', sa.Column('txPassageiro', sa.Text(), nullable=True))
    op.add_column('despesas', sa.Column('txTrecho', sa.Text(), nullable=True))
    op.alter_column('despesas', 'dataDocumento',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('despesas', 'tipoDocumento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('despesas', sa.Column('tipoDocumento', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.alter_column('despesas', 'dataDocumento',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('despesas', 'txTrecho')
    op.drop_column('despesas', 'txPassageiro')
    op.drop_column('despesas', 'numEspecificacaoSubCota')
    op.drop_column('despesas', 'numSubCota')
    # ### end Alembic commands ###
