"""mensagem

Revision ID: 828b077002b1
Revises: 
Create Date: 2026-03-04 14:16:59.477298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '828b077002b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busca_popular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politico_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['politico_id'], ['politicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politico_id')
    )
    op.create_index(op.f('ix_busca_popular_id'), 'busca_popular', ['id'], unique=False)
    op.drop_index(op.f('idx_mandatos_politico'), table_name='mandatos')
    op.drop_table('mandatos')
    op.alter_column('despesas', 'tipo_documento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('despesas', 'num_documento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_constraint(op.f('despesas_cod_documento_unique'), 'despesas', type_='unique')
    op.drop_index(op.f('idx_despesas_ano_mes'), table_name='despesas')
    op.drop_index(op.f('idx_despesas_politico'), table_name='despesas')
    op.drop_index(op.f('idx_despesas_tipo'), table_name='despesas')
    op.create_index(op.f('ix_despesas_ano'), 'despesas', ['ano'], unique=False)
    op.create_index(op.f('ix_despesas_cnpj_cpf_fornecedor'), 'despesas', ['cnpj_cpf_fornecedor'], unique=False)
    op.create_index(op.f('ix_despesas_cod_documento'), 'despesas', ['cod_documento'], unique=True)
    op.create_index(op.f('ix_despesas_mes'), 'despesas', ['mes'], unique=False)
    op.create_index(op.f('ix_despesas_politico_id'), 'despesas', ['politico_id'], unique=False)
    op.drop_constraint(op.f('despesas_politico_id_fkey'), 'despesas', type_='foreignkey')
    op.create_foreign_key(None, 'despesas', 'politicos', ['politico_id'], ['id'], ondelete='CASCADE')
    op.alter_column('discursos', 'fase_evento_titulo',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_discursos_data'), table_name='discursos')
    op.drop_index(op.f('idx_discursos_politico'), table_name='discursos')
    op.drop_index(op.f('idx_discursos_tipo'), table_name='discursos')
    op.drop_index(op.f('uq_discursos_politico_data'), table_name='discursos')
    op.create_index(op.f('ix_discursos_evento_id'), 'discursos', ['evento_id'], unique=False)
    op.create_index(op.f('ix_discursos_politico_id'), 'discursos', ['politico_id'], unique=False)
    op.drop_constraint(op.f('discursos_evento_id_fkey'), 'discursos', type_='foreignkey')
    op.drop_constraint(op.f('discursos_politico_id_fkey'), 'discursos', type_='foreignkey')
    op.create_foreign_key(None, 'discursos', 'eventos', ['evento_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'discursos', 'politicos', ['politico_id'], ['id'], ondelete='CASCADE')
    op.drop_column('discursos', 'uri_evento')
    op.drop_constraint(op.f('eventos_id_camara_key'), 'eventos', type_='unique')
    op.drop_index(op.f('idx_eventos_data'), table_name='eventos')
    op.drop_index(op.f('idx_eventos_situacao'), table_name='eventos')
    op.drop_index(op.f('idx_eventos_tipo'), table_name='eventos')
    op.create_index(op.f('ix_eventos_id_camara'), 'eventos', ['id_camara'], unique=True)
    op.create_index(op.f('ix_eventos_uri'), 'eventos', ['uri'], unique=True)
    op.drop_constraint(op.f('eventos_orgaos_evento_id_fkey'), 'eventos_orgaos', type_='foreignkey')
    op.drop_constraint(op.f('eventos_orgaos_orgao_id_fkey'), 'eventos_orgaos', type_='foreignkey')
    op.create_foreign_key(None, 'eventos_orgaos', 'orgaos', ['orgao_id'], ['id'])
    op.create_foreign_key(None, 'eventos_orgaos', 'eventos', ['evento_id'], ['id'])
    op.drop_constraint(op.f('orgaos_id_camara_key'), 'orgaos', type_='unique')
    op.create_index(op.f('ix_orgaos_id_camara'), 'orgaos', ['id_camara'], unique=True)
    op.create_unique_constraint(None, 'orgaos', ['uri'])
    op.drop_column('orgaos', 'created_at')
    op.alter_column('orgaos_membros', 'politico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_orgaos_membros_orgao_id'), 'orgaos_membros', ['orgao_id'], unique=False)
    op.create_unique_constraint('uq_orgao_orgao_politico', 'orgaos_membros', ['orgao_id', 'politico_id'])
    op.create_index(op.f('ix_orientacoes_votacao_votacao_id'), 'orientacoes_votacao', ['votacao_id'], unique=False)
    op.alter_column('partidos', 'nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('partidos', 'sigla',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('partidos_id_externo_key'), 'partidos', type_='unique')
    op.create_index(op.f('ix_partidos_id_camara'), 'partidos', ['id_camara'], unique=True)
    op.create_unique_constraint(None, 'partidos', ['uri'])
    op.drop_column('partidos', 'created_at')
    op.alter_column('partidos_lideres', 'politico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_partidos_lideres_partido_id'), 'partidos_lideres', ['partido_id'], unique=False)
    op.alter_column('partidos_membros', 'politico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_partidos_membros_partido_id'), 'partidos_membros', ['partido_id'], unique=False)
    op.create_unique_constraint('uq_partido_partido_politico', 'partidos_membros', ['partido_id', 'politico_id'])
    op.alter_column('politicos', 'situacao',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('idx_politicos_id_camara'), table_name='politicos')
    op.drop_index(op.f('idx_politicos_nome'), table_name='politicos')
    op.drop_constraint(op.f('politicos_id_camara_unique'), 'politicos', type_='unique')
    op.drop_constraint(op.f('politicos_id_externo_key'), 'politicos', type_='unique')
    op.create_index(op.f('ix_politicos_id_camara'), 'politicos', ['id_camara'], unique=True)
    op.create_index(op.f('ix_politicos_nome'), 'politicos', ['nome'], unique=False)
    op.drop_column('politicos', 'updated_at')
    op.drop_index(op.f('idx_presencas_data'), table_name='presencas')
    op.drop_index(op.f('idx_presencas_politico_id'), table_name='presencas')
    op.create_index(op.f('ix_presencas_data'), 'presencas', ['data'], unique=False)
    op.create_index(op.f('ix_presencas_politico_id'), 'presencas', ['politico_id'], unique=False)
    op.drop_index(op.f('idx_proposicoes_numero_ano'), table_name='proposicoes')
    op.drop_index(op.f('idx_proposicoes_sigla_tipo'), table_name='proposicoes')
    op.drop_constraint(op.f('proposicoes_id_camara_key'), 'proposicoes', type_='unique')
    op.drop_constraint(op.f('proposicoes_uri_key'), 'proposicoes', type_='unique')
    op.create_index(op.f('ix_proposicoes_ano'), 'proposicoes', ['ano'], unique=False)
    op.create_index(op.f('ix_proposicoes_id_camara'), 'proposicoes', ['id_camara'], unique=True)
    op.create_index(op.f('ix_proposicoes_numero'), 'proposicoes', ['numero'], unique=False)
    op.create_index(op.f('ix_proposicoes_sigla_tipo'), 'proposicoes', ['sigla_tipo'], unique=False)
    op.create_index(op.f('ix_proposicoes_uri'), 'proposicoes', ['uri'], unique=True)
    op.drop_index(op.f('idx_proposicoes_autores_politico'), table_name='proposicoes_autores')
    op.drop_index(op.f('idx_proposicoes_autores_proposicao'), table_name='proposicoes_autores')
    op.create_index(op.f('ix_proposicoes_autores_proposicao_id'), 'proposicoes_autores', ['proposicao_id'], unique=False)
    op.drop_constraint(op.f('proposicoes_temas_proposicao_id_fkey'), 'proposicoes_temas', type_='foreignkey')
    op.drop_constraint(op.f('proposicoes_temas_tema_id_fkey'), 'proposicoes_temas', type_='foreignkey')
    op.create_foreign_key(None, 'proposicoes_temas', 'temas', ['tema_id'], ['id'])
    op.create_foreign_key(None, 'proposicoes_temas', 'proposicoes', ['proposicao_id'], ['id'])
    op.alter_column('temas', 'cod_tema',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('temas', 'tema',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_index(op.f('idx_temas_tema'), table_name='temas')
    op.drop_constraint(op.f('temas_cod_tema_key'), 'temas', type_='unique')
    op.create_index(op.f('ix_temas_cod_tema'), 'temas', ['cod_tema'], unique=True)
    op.create_index(op.f('ix_temas_tema'), 'temas', ['tema'], unique=False)
    op.drop_index(op.f('idx_tramitacoes_data'), table_name='tramitacoes')
    op.drop_index(op.f('idx_tramitacoes_proposicao'), table_name='tramitacoes')
    op.create_index(op.f('ix_tramitacoes_data_hora'), 'tramitacoes', ['data_hora'], unique=False)
    op.create_index(op.f('ix_tramitacoes_proposicao_id'), 'tramitacoes', ['proposicao_id'], unique=False)
    op.drop_index(op.f('idx_verbas_ano'), table_name='verbas_gabinete')
    op.drop_index(op.f('idx_verbas_id_camara'), table_name='verbas_gabinete')
    op.drop_index(op.f('idx_verbas_mes'), table_name='verbas_gabinete')
    op.drop_index(op.f('idx_verbas_politico_id'), table_name='verbas_gabinete')
    op.create_index(op.f('ix_verbas_gabinete_ano'), 'verbas_gabinete', ['ano'], unique=False)
    op.create_index(op.f('ix_verbas_gabinete_id'), 'verbas_gabinete', ['id'], unique=False)
    op.create_index(op.f('ix_verbas_gabinete_id_camara'), 'verbas_gabinete', ['id_camara'], unique=False)
    op.create_index(op.f('ix_verbas_gabinete_mes'), 'verbas_gabinete', ['mes'], unique=False)
    op.create_index(op.f('ix_verbas_gabinete_politico_id'), 'verbas_gabinete', ['politico_id'], unique=False)
    op.drop_index(op.f('idx_votacoes_prop_data'), table_name='votacoes')
    op.drop_index(op.f('idx_votacoes_proposicao_id'), table_name='votacoes')
    op.drop_constraint(op.f('votacoes_id_camara_key'), 'votacoes', type_='unique')
    op.create_index(op.f('ix_votacoes_id_camara'), 'votacoes', ['id_camara'], unique=True)
    op.create_index(op.f('ix_votacoes_proposicao_id'), 'votacoes', ['proposicao_id'], unique=False)
    op.drop_constraint(op.f('fk_votacoes_orgao'), 'votacoes', type_='foreignkey')
    op.create_foreign_key(None, 'votacoes', 'proposicoes', ['proposicao_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votacoes', 'orgaos', ['orgao_id'], ['id'])
    op.alter_column('votos', 'sigla_uf',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.drop_index(op.f('idx_votos_politico'), table_name='votos')
    op.drop_index(op.f('idx_votos_votacao'), table_name='votos')
    op.drop_constraint(op.f('votos_votacao_id_politico_id_key'), 'votos', type_='unique')
    op.create_index(op.f('ix_votos_politico_id'), 'votos', ['politico_id'], unique=False)
    op.create_index(op.f('ix_votos_votacao_id'), 'votos', ['votacao_id'], unique=False)
    op.create_unique_constraint('uq_voto_votacao_politico', 'votos', ['votacao_id', 'politico_id'])
    op.drop_constraint(op.f('votos_politico_id_fkey'), 'votos', type_='foreignkey')
    op.drop_constraint(op.f('votos_votacao_id_fkey'), 'votos', type_='foreignkey')
    op.create_foreign_key(None, 'votos', 'politicos', ['politico_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votos', 'votacoes', ['votacao_id'], ['id'], ondelete='CASCADE')
    op.drop_column('votos', 'voto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votos', sa.Column('voto', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'votos', type_='foreignkey')
    op.drop_constraint(None, 'votos', type_='foreignkey')
    op.create_foreign_key(op.f('votos_votacao_id_fkey'), 'votos', 'votacoes', ['votacao_id'], ['id'])
    op.create_foreign_key(op.f('votos_politico_id_fkey'), 'votos', 'politicos', ['politico_id'], ['id'])
    op.drop_constraint('uq_voto_votacao_politico', 'votos', type_='unique')
    op.drop_index(op.f('ix_votos_votacao_id'), table_name='votos')
    op.drop_index(op.f('ix_votos_politico_id'), table_name='votos')
    op.create_unique_constraint(op.f('votos_votacao_id_politico_id_key'), 'votos', ['votacao_id', 'politico_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_votos_votacao'), 'votos', ['votacao_id'], unique=False)
    op.create_index(op.f('idx_votos_politico'), 'votos', ['politico_id'], unique=False)
    op.alter_column('votos', 'sigla_uf',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True)
    op.drop_constraint(None, 'votacoes', type_='foreignkey')
    op.drop_constraint(None, 'votacoes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_votacoes_orgao'), 'votacoes', 'orgaos', ['orgao_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_votacoes_proposicao_id'), table_name='votacoes')
    op.drop_index(op.f('ix_votacoes_id_camara'), table_name='votacoes')
    op.create_unique_constraint(op.f('votacoes_id_camara_key'), 'votacoes', ['id_camara'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_votacoes_proposicao_id'), 'votacoes', ['proposicao_id'], unique=False)
    op.create_index(op.f('idx_votacoes_prop_data'), 'votacoes', ['proposicao_id', sa.literal_column('data DESC')], unique=False)
    op.drop_index(op.f('ix_verbas_gabinete_politico_id'), table_name='verbas_gabinete')
    op.drop_index(op.f('ix_verbas_gabinete_mes'), table_name='verbas_gabinete')
    op.drop_index(op.f('ix_verbas_gabinete_id_camara'), table_name='verbas_gabinete')
    op.drop_index(op.f('ix_verbas_gabinete_id'), table_name='verbas_gabinete')
    op.drop_index(op.f('ix_verbas_gabinete_ano'), table_name='verbas_gabinete')
    op.create_index(op.f('idx_verbas_politico_id'), 'verbas_gabinete', ['politico_id'], unique=False)
    op.create_index(op.f('idx_verbas_mes'), 'verbas_gabinete', ['mes'], unique=False)
    op.create_index(op.f('idx_verbas_id_camara'), 'verbas_gabinete', ['id_camara'], unique=False)
    op.create_index(op.f('idx_verbas_ano'), 'verbas_gabinete', ['ano'], unique=False)
    op.drop_index(op.f('ix_tramitacoes_proposicao_id'), table_name='tramitacoes')
    op.drop_index(op.f('ix_tramitacoes_data_hora'), table_name='tramitacoes')
    op.create_index(op.f('idx_tramitacoes_proposicao'), 'tramitacoes', ['proposicao_id'], unique=False)
    op.create_index(op.f('idx_tramitacoes_data'), 'tramitacoes', ['data_hora'], unique=False)
    op.drop_index(op.f('ix_temas_tema'), table_name='temas')
    op.drop_index(op.f('ix_temas_cod_tema'), table_name='temas')
    op.create_unique_constraint(op.f('temas_cod_tema_key'), 'temas', ['cod_tema'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_temas_tema'), 'temas', ['tema'], unique=False)
    op.alter_column('temas', 'tema',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('temas', 'cod_tema',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'proposicoes_temas', type_='foreignkey')
    op.drop_constraint(None, 'proposicoes_temas', type_='foreignkey')
    op.create_foreign_key(op.f('proposicoes_temas_tema_id_fkey'), 'proposicoes_temas', 'temas', ['tema_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('proposicoes_temas_proposicao_id_fkey'), 'proposicoes_temas', 'proposicoes', ['proposicao_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_proposicoes_autores_proposicao_id'), table_name='proposicoes_autores')
    op.create_index(op.f('idx_proposicoes_autores_proposicao'), 'proposicoes_autores', ['proposicao_id'], unique=False)
    op.create_index(op.f('idx_proposicoes_autores_politico'), 'proposicoes_autores', ['politico_id'], unique=False)
    op.drop_index(op.f('ix_proposicoes_uri'), table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_sigla_tipo'), table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_numero'), table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_id_camara'), table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_ano'), table_name='proposicoes')
    op.create_unique_constraint(op.f('proposicoes_uri_key'), 'proposicoes', ['uri'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('proposicoes_id_camara_key'), 'proposicoes', ['id_camara'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_proposicoes_sigla_tipo'), 'proposicoes', ['sigla_tipo'], unique=False)
    op.create_index(op.f('idx_proposicoes_numero_ano'), 'proposicoes', ['numero', 'ano'], unique=False)
    op.drop_index(op.f('ix_presencas_politico_id'), table_name='presencas')
    op.drop_index(op.f('ix_presencas_data'), table_name='presencas')
    op.create_index(op.f('idx_presencas_politico_id'), 'presencas', ['politico_id'], unique=False)
    op.create_index(op.f('idx_presencas_data'), 'presencas', ['data'], unique=False)
    op.add_column('politicos', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_politicos_nome'), table_name='politicos')
    op.drop_index(op.f('ix_politicos_id_camara'), table_name='politicos')
    op.create_unique_constraint(op.f('politicos_id_externo_key'), 'politicos', ['id_camara'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('politicos_id_camara_unique'), 'politicos', ['id_camara'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_politicos_nome'), 'politicos', ['nome'], unique=False)
    op.create_index(op.f('idx_politicos_id_camara'), 'politicos', ['id_camara'], unique=True)
    op.alter_column('politicos', 'situacao',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_constraint('uq_partido_partido_politico', 'partidos_membros', type_='unique')
    op.drop_index(op.f('ix_partidos_membros_partido_id'), table_name='partidos_membros')
    op.alter_column('partidos_membros', 'politico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_partidos_lideres_partido_id'), table_name='partidos_lideres')
    op.alter_column('partidos_lideres', 'politico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('partidos', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'partidos', type_='unique')
    op.drop_index(op.f('ix_partidos_id_camara'), table_name='partidos')
    op.create_unique_constraint(op.f('partidos_id_externo_key'), 'partidos', ['id_camara'], postgresql_nulls_not_distinct=False)
    op.alter_column('partidos', 'sigla',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('partidos', 'nome',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_orientacoes_votacao_votacao_id'), table_name='orientacoes_votacao')
    op.drop_constraint('uq_orgao_orgao_politico', 'orgaos_membros', type_='unique')
    op.drop_index(op.f('ix_orgaos_membros_orgao_id'), table_name='orgaos_membros')
    op.alter_column('orgaos_membros', 'politico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('orgaos', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orgaos', type_='unique')
    op.drop_index(op.f('ix_orgaos_id_camara'), table_name='orgaos')
    op.create_unique_constraint(op.f('orgaos_id_camara_key'), 'orgaos', ['id_camara'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'eventos_orgaos', type_='foreignkey')
    op.drop_constraint(None, 'eventos_orgaos', type_='foreignkey')
    op.create_foreign_key(op.f('eventos_orgaos_orgao_id_fkey'), 'eventos_orgaos', 'orgaos', ['orgao_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('eventos_orgaos_evento_id_fkey'), 'eventos_orgaos', 'eventos', ['evento_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_eventos_uri'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_id_camara'), table_name='eventos')
    op.create_index(op.f('idx_eventos_tipo'), 'eventos', ['descricao_tipo'], unique=False)
    op.create_index(op.f('idx_eventos_situacao'), 'eventos', ['situacao'], unique=False)
    op.create_index(op.f('idx_eventos_data'), 'eventos', ['data_hora_inicio'], unique=False)
    op.create_unique_constraint(op.f('eventos_id_camara_key'), 'eventos', ['id_camara'], postgresql_nulls_not_distinct=False)
    op.add_column('discursos', sa.Column('uri_evento', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'discursos', type_='foreignkey')
    op.drop_constraint(None, 'discursos', type_='foreignkey')
    op.create_foreign_key(op.f('discursos_politico_id_fkey'), 'discursos', 'politicos', ['politico_id'], ['id'])
    op.create_foreign_key(op.f('discursos_evento_id_fkey'), 'discursos', 'eventos', ['evento_id'], ['id'])
    op.drop_index(op.f('ix_discursos_politico_id'), table_name='discursos')
    op.drop_index(op.f('ix_discursos_evento_id'), table_name='discursos')
    op.create_index(op.f('uq_discursos_politico_data'), 'discursos', ['politico_id', 'data_hora_inicio'], unique=True)
    op.create_index(op.f('idx_discursos_tipo'), 'discursos', ['tipo_discurso'], unique=False)
    op.create_index(op.f('idx_discursos_politico'), 'discursos', ['politico_id'], unique=False)
    op.create_index(op.f('idx_discursos_data'), 'discursos', ['data_hora_inicio'], unique=False)
    op.alter_column('discursos', 'fase_evento_titulo',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.drop_constraint(None, 'despesas', type_='foreignkey')
    op.create_foreign_key(op.f('despesas_politico_id_fkey'), 'despesas', 'politicos', ['politico_id'], ['id'])
    op.drop_index(op.f('ix_despesas_politico_id'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_mes'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_cod_documento'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_cnpj_cpf_fornecedor'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_ano'), table_name='despesas')
    op.create_index(op.f('idx_despesas_tipo'), 'despesas', ['tipo_despesa'], unique=False)
    op.create_index(op.f('idx_despesas_politico'), 'despesas', ['politico_id'], unique=False)
    op.create_index(op.f('idx_despesas_ano_mes'), 'despesas', ['ano', 'mes'], unique=False)
    op.create_unique_constraint(op.f('despesas_cod_documento_unique'), 'despesas', ['cod_documento'], postgresql_nulls_not_distinct=False)
    op.alter_column('despesas', 'num_documento',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('despesas', 'tipo_documento',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_table('mandatos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('politico_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('partido_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('legislatura', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('situacao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], name=op.f('mandatos_partido_id_fkey')),
    sa.ForeignKeyConstraint(['politico_id'], ['politicos.id'], name=op.f('mandatos_politico_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mandatos_pkey'))
    )
    op.create_index(op.f('idx_mandatos_politico'), 'mandatos', ['politico_id'], unique=False)
    op.drop_index(op.f('ix_busca_popular_id'), table_name='busca_popular')
    op.drop_table('busca_popular')
    # ### end Alembic commands ###
