"""resumoIA

Revision ID: d9a27be33e0a
Revises: 556202159cfb
Create Date: 2026-03-25 15:08:45.688226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a27be33e0a'
down_revision: Union[str, Sequence[str], None] = '556202159cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumoIa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('resumoFeitos', sa.Text(), nullable=True),
    sa.Column('resumoEspectro', sa.Text(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idDeputado')
    )
    op.create_index(op.f('ix_resumoIa_id'), 'resumoIa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumoIa_id'), table_name='resumoIa')
    op.drop_table('resumoIa')
    # ### end Alembic commands ###
