# script injest banco
FROM python:3.11-slim

WORKDIR /app/injest_banco

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY injest_banco/ ./injest_banco/

CMD ["python", "etl_camara.py", "--update"]