# configuração usada no servidor caseiro com tunnel cloudflare
upstream api_backend {
    server api:8000;
    keepalive 32;
}

upstream frontend_backend {
    server frontend:3000;
    keepalive 16;
}

# Rate Limiting: 10MB armazena ~160.000 IPs. 30 requisições/segundo por IP com burst de 40.
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=30r/s;
limit_req_status 429;

server {
    listen 80;
    server_name quemvota.com.br www.quemvota.com.br;

    # Cabeçalhos de segurança (a Cloudflare já faz muito disso, mas é bom manter)
    add_header X-Frame-Options        "SAMEORIGIN"   always;
    add_header X-Content-Type-Options "nosniff"      always;
    add_header Referrer-Policy        "strict-origin" always;

    # O Cloudflare passa o IP real do usuário nestes headers
    set_real_ip_from 0.0.0.0/0; # Em produção, restrinja aos IPs da Cloudflare
    real_ip_header CF-Connecting-IP;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;

    location / {
        proxy_pass         http://frontend_backend;
        proxy_http_version 1.1;
        proxy_set_header   Connection        "";
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /api/ {
        limit_req          zone=api_limit burst=40 nodelay;
        proxy_pass         http://api_backend/;
        proxy_http_version 1.1;
        proxy_set_header   Connection        "";
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }
}

