"""add_historico_mandatos_externos_tramitacoes_uq

Revision ID: 8052abf4e149
Revises: f5e6d7c8b9a0
Create Date: 2026-09-05 13:29:39.683605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8052abf4e149'
down_revision: Union[str, Sequence[str], None] = 'f5e6d7c8b9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deputadosHistorico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('idLegislatura', sa.Integer(), nullable=True),
    sa.Column('dataInicio', sa.DateTime(), nullable=False),
    sa.Column('dataFim', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('siglaPartido', sa.String(length=50), nullable=True),
    sa.Column('siglaUF', sa.CHAR(length=2), nullable=True),
    sa.Column('idPartido', sa.Integer(), nullable=True),
    sa.Column('condicao', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idLegislatura'], ['legislaturas.idLegislatura'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idDeputado', 'idLegislatura', 'dataInicio', 'descricao', name='uq_deputado_historico')
    )
    op.create_index(op.f('ix_deputadosHistorico_dataInicio'), 'deputadosHistorico', ['dataInicio'], unique=False)
    op.create_index(op.f('ix_deputadosHistorico_idDeputado'), 'deputadosHistorico', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_deputadosHistorico_idLegislatura'), 'deputadosHistorico', ['idLegislatura'], unique=False)
    op.create_index(op.f('ix_deputadosHistorico_siglaPartido'), 'deputadosHistorico', ['siglaPartido'], unique=False)
    op.create_index(op.f('ix_deputadosHistorico_siglaUF'), 'deputadosHistorico', ['siglaUF'], unique=False)
    op.create_table('deputadosMandatosExternos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('siglaUF', sa.CHAR(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=150), nullable=True),
    sa.Column('anoInicio', sa.Integer(), nullable=True),
    sa.Column('anoFim', sa.Integer(), nullable=True),
    sa.Column('siglaPartidoEleicao', sa.String(length=50), nullable=True),
    sa.Column('uriPartidoEleicao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idDeputado', 'cargo', 'siglaUF', 'anoInicio', name='uq_deputado_mandato_externo')
    )
    op.create_index(op.f('ix_deputadosMandatosExternos_idDeputado'), 'deputadosMandatosExternos', ['idDeputado'], unique=False)
    op.create_unique_constraint('uq_tramitacao_prop_seq_data', 'tramitacoes', ['idProposicao', 'sequencia', 'dataHora'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tramitacao_prop_seq_data', 'tramitacoes', type_='unique')
    op.drop_index(op.f('ix_deputadosMandatosExternos_idDeputado'), table_name='deputadosMandatosExternos')
    op.drop_table('deputadosMandatosExternos')
    op.drop_index(op.f('ix_deputadosHistorico_siglaUF'), table_name='deputadosHistorico')
    op.drop_index(op.f('ix_deputadosHistorico_siglaPartido'), table_name='deputadosHistorico')
    op.drop_index(op.f('ix_deputadosHistorico_idLegislatura'), table_name='deputadosHistorico')
    op.drop_index(op.f('ix_deputadosHistorico_idDeputado'), table_name='deputadosHistorico')
    op.drop_index(op.f('ix_deputadosHistorico_dataInicio'), table_name='deputadosHistorico')
    op.drop_table('deputadosHistorico')
    # ### end Alembic commands ###
