"""new

Revision ID: 97b9b773c7ab
Revises: 
Create Date: 2026-03-07 01:58:12.746553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b9b773c7ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCamara', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('urlDocumentoPauta', sa.Text(), nullable=True),
    sa.Column('dataHoraInicio', sa.DateTime(), nullable=True),
    sa.Column('dataHoraFim', sa.DateTime(), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('descricaoTipo', sa.String(length=100), nullable=True),
    sa.Column('localExterno', sa.Text(), nullable=True),
    sa.Column('localCamaraNome', sa.String(length=200), nullable=True),
    sa.Column('localCamaraPredio', sa.String(length=100), nullable=True),
    sa.Column('localCamaraSala', sa.String(length=50), nullable=True),
    sa.Column('localCamaraAndar', sa.String(length=50), nullable=True),
    sa.Column('urlEvento', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_eventos_dataHoraInicio'), 'eventos', ['dataHoraInicio'], unique=False)
    op.create_index(op.f('ix_eventos_idCamara'), 'eventos', ['idCamara'], unique=True)
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ponto', sa.String(length=20), nullable=False),
    sa.Column('codGrupo', sa.Integer(), nullable=True),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('lotacao', sa.String(length=300), nullable=True),
    sa.Column('atoNomeacao', sa.String(length=100), nullable=True),
    sa.Column('dataNomeacao', sa.Date(), nullable=True),
    sa.Column('dataInicioHistorico', sa.Date(), nullable=True),
    sa.Column('dataPubNomeacao', sa.Date(), nullable=True),
    sa.Column('funcao', sa.String(length=200), nullable=True),
    sa.Column('uriLotacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_nome'), 'funcionarios', ['nome'], unique=False)
    op.create_index(op.f('ix_funcionarios_ponto'), 'funcionarios', ['ponto'], unique=True)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCamara', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('nomeGrupo', sa.String(length=200), nullable=True),
    sa.Column('anoCriacao', sa.Integer(), nullable=True),
    sa.Column('projetoTitulo', sa.String(length=100), nullable=True),
    sa.Column('projetoUri', sa.Text(), nullable=True),
    sa.Column('resolucaoTitulo', sa.String(length=100), nullable=True),
    sa.Column('resolucaoUri', sa.Text(), nullable=True),
    sa.Column('subvencionado', sa.Boolean(), nullable=True),
    sa.Column('grupoMisto', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('ultimoStatus_idLegislatura', sa.Integer(), nullable=True),
    sa.Column('ultimoStatus_dataStatus', sa.DateTime(), nullable=True),
    sa.Column('ultimoStatus_presidenteNome', sa.String(length=200), nullable=True),
    sa.Column('ultimoStatus_presidenteUri', sa.Text(), nullable=True),
    sa.Column('ultimoStatus_documento', sa.String(length=100), nullable=True),
    sa.Column('ultimoStatus_oficioTitulo', sa.String(length=200), nullable=True),
    sa.Column('ultimoStatus_oficioUri', sa.Text(), nullable=True),
    sa.Column('ultimoStatus_oficioAutorTipo', sa.String(length=50), nullable=True),
    sa.Column('ultimoStatus_oficioAutorNome', sa.String(length=200), nullable=True),
    sa.Column('ultimoStatus_oficioAutorUri', sa.Text(), nullable=True),
    sa.Column('ultimoStatus_oficioDataApresentacao', sa.DateTime(), nullable=True),
    sa.Column('ultimoStatus_oficioDataPublicacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_grupos_ativo'), 'grupos', ['ativo'], unique=False)
    op.create_index(op.f('ix_grupos_idCamara'), 'grupos', ['idCamara'], unique=True)
    op.create_table('legislaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idLegislatura', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('dataInicio', sa.Date(), nullable=True),
    sa.Column('dataFim', sa.Date(), nullable=True),
    sa.Column('anoEleicao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislaturas_idLegislatura'), 'legislaturas', ['idLegislatura'], unique=True)
    op.create_table('licitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idLicitacao', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('numProcesso', sa.Integer(), nullable=True),
    sa.Column('anoProcesso', sa.Integer(), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=100), nullable=True),
    sa.Column('vlrEstimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vlrContratado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vlrPago', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dataAutorizacao', sa.Date(), nullable=True),
    sa.Column('dataPublicacao', sa.Date(), nullable=True),
    sa.Column('dataAbertura', sa.Date(), nullable=True),
    sa.Column('numItens', sa.Integer(), nullable=True),
    sa.Column('numUnidades', sa.Integer(), nullable=True),
    sa.Column('numPropostas', sa.Integer(), nullable=True),
    sa.Column('numContratos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoes_ano'), 'licitacoes', ['ano'], unique=False)
    op.create_index('ix_licitacoes_ano_sit', 'licitacoes', ['ano', 'situacao'], unique=False)
    op.create_index(op.f('ix_licitacoes_idLicitacao'), 'licitacoes', ['idLicitacao'], unique=True)
    op.create_table('orgaos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCamara', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('sigla', sa.String(length=50), nullable=True),
    sa.Column('apelido', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('nomePublicacao', sa.Text(), nullable=True),
    sa.Column('codTipoOrgao', sa.Integer(), nullable=True),
    sa.Column('tipoOrgao', sa.String(length=100), nullable=True),
    sa.Column('casa', sa.String(length=50), nullable=True),
    sa.Column('sala', sa.String(length=50), nullable=True),
    sa.Column('dataInicio', sa.Date(), nullable=True),
    sa.Column('dataInstalacao', sa.Date(), nullable=True),
    sa.Column('dataFim', sa.Date(), nullable=True),
    sa.Column('dataFimOriginal', sa.Date(), nullable=True),
    sa.Column('codSituacao', sa.Integer(), nullable=True),
    sa.Column('descricaoSituacao', sa.String(length=100), nullable=True),
    sa.Column('urlWebsite', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_orgaos_idCamara'), 'orgaos', ['idCamara'], unique=True)
    op.create_index(op.f('ix_orgaos_sigla'), 'orgaos', ['sigla'], unique=False)
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCamara', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=False),
    sa.Column('numeroEleitoral', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.String(length=100), nullable=True),
    sa.Column('totalMembros', sa.Integer(), nullable=True),
    sa.Column('totalPosse', sa.Integer(), nullable=True),
    sa.Column('urlFacebook', sa.Text(), nullable=True),
    sa.Column('urlLogo', sa.Text(), nullable=True),
    sa.Column('urlWebsite', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_partidos_idCamara'), 'partidos', ['idCamara'], unique=True)
    op.create_index(op.f('ix_partidos_sigla'), 'partidos', ['sigla'], unique=False)
    op.create_table('proposicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCamara', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('siglaTipo', sa.String(length=50), nullable=True),
    sa.Column('codTipo', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('descricaoTipo', sa.Text(), nullable=True),
    sa.Column('ementa', sa.Text(), nullable=True),
    sa.Column('ementaDetalhada', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('dataApresentacao', sa.DateTime(), nullable=True),
    sa.Column('uriOrgaoNumerador', sa.Text(), nullable=True),
    sa.Column('uriPropAnterior', sa.Text(), nullable=True),
    sa.Column('uriPropPrincipal', sa.Text(), nullable=True),
    sa.Column('uriPropPosterior', sa.Text(), nullable=True),
    sa.Column('urlInteiroTeor', sa.Text(), nullable=True),
    sa.Column('urnFinal', sa.String(length=200), nullable=True),
    sa.Column('ultimoStatus_dataHora', sa.DateTime(), nullable=True),
    sa.Column('ultimoStatus_sequencia', sa.Integer(), nullable=True),
    sa.Column('ultimoStatus_uriRelator', sa.Text(), nullable=True),
    sa.Column('ultimoStatus_idOrgao', sa.Integer(), nullable=True),
    sa.Column('ultimoStatus_siglaOrgao', sa.String(length=50), nullable=True),
    sa.Column('ultimoStatus_uriOrgao', sa.Text(), nullable=True),
    sa.Column('ultimoStatus_regime', sa.String(length=200), nullable=True),
    sa.Column('ultimoStatus_descricaoTramitacao', sa.String(length=200), nullable=True),
    sa.Column('ultimoStatus_idTipoTramitacao', sa.Integer(), nullable=True),
    sa.Column('ultimoStatus_descricaoSituacao', sa.String(length=150), nullable=True),
    sa.Column('ultimoStatus_idSituacao', sa.Integer(), nullable=True),
    sa.Column('ultimoStatus_despacho', sa.Text(), nullable=True),
    sa.Column('ultimoStatus_apreciacao', sa.String(length=200), nullable=True),
    sa.Column('ultimoStatus_url', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposicoes_ano'), 'proposicoes', ['ano'], unique=False)
    op.create_index(op.f('ix_proposicoes_idCamara'), 'proposicoes', ['idCamara'], unique=True)
    op.create_index(op.f('ix_proposicoes_numero'), 'proposicoes', ['numero'], unique=False)
    op.create_index(op.f('ix_proposicoes_siglaTipo'), 'proposicoes', ['siglaTipo'], unique=False)
    op.create_index('ix_proposicoes_tipo_ano', 'proposicoes', ['siglaTipo', 'ano'], unique=False)
    op.create_index(op.f('ix_proposicoes_uri'), 'proposicoes', ['uri'], unique=True)
    op.create_table('tecadCategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codCategoria', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.Column('codSubCategoria', sa.Integer(), nullable=True),
    sa.Column('subCategoria', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codCategoria', 'codSubCategoria', name='uq_tecad_cat_subcat')
    )
    op.create_index(op.f('ix_tecadCategorias_codCategoria'), 'tecadCategorias', ['codCategoria'], unique=False)
    op.create_index(op.f('ix_tecadCategorias_codSubCategoria'), 'tecadCategorias', ['codSubCategoria'], unique=False)
    op.create_table('tecadTermos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codTermo', sa.Integer(), nullable=True),
    sa.Column('termo', sa.Text(), nullable=True),
    sa.Column('categorias', sa.Text(), nullable=True),
    sa.Column('subcategorias', sa.Text(), nullable=True),
    sa.Column('notasExplicativas', sa.Text(), nullable=True),
    sa.Column('notasHistoricas', sa.Text(), nullable=True),
    sa.Column('notasAplicativas', sa.Text(), nullable=True),
    sa.Column('fontes', sa.Text(), nullable=True),
    sa.Column('use', sa.Text(), nullable=True),
    sa.Column('usadoPara', sa.Text(), nullable=True),
    sa.Column('termosEspecificos', sa.Text(), nullable=True),
    sa.Column('termosGenericos', sa.Text(), nullable=True),
    sa.Column('termosRelacionados', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecadTermos_codTermo'), 'tecadTermos', ['codTermo'], unique=True)
    op.create_index(op.f('ix_tecadTermos_termo'), 'tecadTermos', ['termo'], unique=False)
    op.create_table('temas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codTema', sa.Integer(), nullable=True),
    sa.Column('tema', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temas_codTema'), 'temas', ['codTema'], unique=True)
    op.create_index(op.f('ix_temas_tema'), 'temas', ['tema'], unique=False)
    op.create_table('deputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCamara', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nomeCivil', sa.String(length=200), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('siglaSexo', sa.CHAR(length=1), nullable=True),
    sa.Column('idLegislaturaInicial', sa.Integer(), nullable=True),
    sa.Column('idLegislaturaFinal', sa.Integer(), nullable=True),
    sa.Column('dataNascimento', sa.Date(), nullable=True),
    sa.Column('dataFalecimento', sa.Date(), nullable=True),
    sa.Column('ufNascimento', sa.CHAR(length=2), nullable=True),
    sa.Column('municipioNascimento', sa.String(length=100), nullable=True),
    sa.Column('siglaUF', sa.CHAR(length=2), nullable=True),
    sa.Column('siglaPartido', sa.String(length=20), nullable=True),
    sa.Column('idPartido', sa.Integer(), nullable=True),
    sa.Column('escolaridade', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('condicaoEleitoral', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefoneGabinete', sa.String(length=30), nullable=True),
    sa.Column('emailGabinete', sa.String(length=200), nullable=True),
    sa.Column('urlFoto', sa.Text(), nullable=True),
    sa.Column('urlRedeSocial', sa.Text(), nullable=True),
    sa.Column('urlWebsite', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idLegislaturaFinal'], ['legislaturas.idLegislatura'], ),
    sa.ForeignKeyConstraint(['idLegislaturaInicial'], ['legislaturas.idLegislatura'], ),
    sa.ForeignKeyConstraint(['idPartido'], ['partidos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_deputados_idCamara'), 'deputados', ['idCamara'], unique=True)
    op.create_index(op.f('ix_deputados_idLegislaturaFinal'), 'deputados', ['idLegislaturaFinal'], unique=False)
    op.create_index(op.f('ix_deputados_nome'), 'deputados', ['nome'], unique=False)
    op.create_index(op.f('ix_deputados_siglaPartido'), 'deputados', ['siglaPartido'], unique=False)
    op.create_index(op.f('ix_deputados_siglaUF'), 'deputados', ['siglaUF'], unique=False)
    op.create_index(op.f('ix_deputados_slug'), 'deputados', ['slug'], unique=True)
    op.create_table('eventosOrgaos',
    sa.Column('idEvento', sa.Integer(), nullable=False),
    sa.Column('idOrgao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEvento'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idOrgao'], ['orgaos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idEvento', 'idOrgao')
    )
    op.create_table('eventosRequerimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEvento', sa.Integer(), nullable=False),
    sa.Column('tituloRequerimento', sa.String(length=200), nullable=True),
    sa.Column('uriRequerimento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idEvento'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventosRequerimentos_idEvento'), 'eventosRequerimentos', ['idEvento'], unique=False)
    op.create_table('gruposHistorico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idGrupo', sa.Integer(), nullable=False),
    sa.Column('idLegislatura', sa.Integer(), nullable=True),
    sa.Column('dataStatus', sa.DateTime(), nullable=True),
    sa.Column('documentoSgm', sa.String(length=100), nullable=True),
    sa.Column('presidente', sa.String(length=200), nullable=True),
    sa.Column('presidenteUri', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('oficioTitulo', sa.String(length=200), nullable=True),
    sa.Column('oficioAutorTipo', sa.Text(), nullable=True),
    sa.Column('oficioAutor', sa.String(length=200), nullable=True),
    sa.Column('oficioAutorUri', sa.Text(), nullable=True),
    sa.Column('oficioDataApresentacao', sa.DateTime(), nullable=True),
    sa.Column('oficioDataPublicacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idGrupo'], ['grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gruposHistorico_idGrupo'), 'gruposHistorico', ['idGrupo'], unique=False)
    op.create_table('licitacoesContratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idLicitacao', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('numContrato', sa.Integer(), nullable=True),
    sa.Column('anoContrato', sa.Integer(), nullable=True),
    sa.Column('tipoContrato', sa.String(length=50), nullable=True),
    sa.Column('situacaoContrato', sa.String(length=50), nullable=True),
    sa.Column('vlrOriginal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vlrTotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('dataAssinatura', sa.Date(), nullable=True),
    sa.Column('dataPublicacao', sa.Date(), nullable=True),
    sa.Column('dataInicioVigenciaOriginal', sa.Date(), nullable=True),
    sa.Column('dataFimVigenciaOriginal', sa.Date(), nullable=True),
    sa.Column('dataFimUltimaVigencia', sa.Date(), nullable=True),
    sa.Column('fornecedorCpfCnpj', sa.String(length=20), nullable=True),
    sa.Column('fornecedorNome', sa.Text(), nullable=True),
    sa.Column('fornecedorEndereco', sa.Text(), nullable=True),
    sa.Column('fornecedorCidade', sa.String(length=100), nullable=True),
    sa.Column('fornecedorSiglaUF', sa.CHAR(length=2), nullable=True),
    sa.Column('numSeqArquivoInstrContratual', sa.Integer(), nullable=True),
    sa.Column('txtNomeArquivo', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['idLicitacao'], ['licitacoes.idLicitacao'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoesContratos_fornecedorCpfCnpj'), 'licitacoesContratos', ['fornecedorCpfCnpj'], unique=False)
    op.create_index(op.f('ix_licitacoesContratos_idLicitacao'), 'licitacoesContratos', ['idLicitacao'], unique=False)
    op.create_table('licitacoesItens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idLicitacao', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('numItem', sa.Integer(), nullable=True),
    sa.Column('numSubitem', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('especificacao', sa.Text(), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('qtdLicitada', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('vlrUnitarioEstimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('qtdContratada', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('vlrUnitarioContratado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vlrTotalContratado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fornecedorCpfCnpj', sa.String(length=20), nullable=True),
    sa.Column('fornecedorNome', sa.Text(), nullable=True),
    sa.Column('uriContrato', sa.Text(), nullable=True),
    sa.Column('numContrato', sa.Integer(), nullable=True),
    sa.Column('anoContrato', sa.Integer(), nullable=True),
    sa.Column('tipoContrato', sa.String(length=50), nullable=True),
    sa.Column('situacaoItem', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('naturezaDespesa', sa.Text(), nullable=True),
    sa.Column('programaTrabalho', sa.Text(), nullable=True),
    sa.Column('codPTRES', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['idLicitacao'], ['licitacoes.idLicitacao'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoesItens_fornecedorCpfCnpj'), 'licitacoesItens', ['fornecedorCpfCnpj'], unique=False)
    op.create_index(op.f('ix_licitacoesItens_idLicitacao'), 'licitacoesItens', ['idLicitacao'], unique=False)
    op.create_table('licitacoesPedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idLicitacao', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('tipoRegistro', sa.String(length=50), nullable=True),
    sa.Column('numPedido', sa.Integer(), nullable=True),
    sa.Column('anoPedido', sa.Integer(), nullable=True),
    sa.Column('dataHoraCadastro', sa.DateTime(), nullable=True),
    sa.Column('idOrgao', sa.Integer(), nullable=True),
    sa.Column('orgao', sa.String(length=300), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idLicitacao'], ['licitacoes.idLicitacao'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoesPedidos_ano'), 'licitacoesPedidos', ['ano'], unique=False)
    op.create_index(op.f('ix_licitacoesPedidos_idLicitacao'), 'licitacoesPedidos', ['idLicitacao'], unique=False)
    op.create_table('licitacoesPropostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idLicitacao', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('numItem', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('numSubitens', sa.Integer(), nullable=True),
    sa.Column('unidadesLicitadas', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('vlrEstimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unidadesProposta', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('vlrProposta', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('numProposta', sa.Integer(), nullable=True),
    sa.Column('marcaProposta', sa.String(length=200), nullable=True),
    sa.Column('fornecedorCpfCnpj', sa.String(length=20), nullable=True),
    sa.Column('fornecedorSituacao', sa.String(length=50), nullable=True),
    sa.Column('dataProposta', sa.Date(), nullable=True),
    sa.Column('diasValidadeProposta', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('urlDocumento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idLicitacao'], ['licitacoes.idLicitacao'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoesPropostas_fornecedorCpfCnpj'), 'licitacoesPropostas', ['fornecedorCpfCnpj'], unique=False)
    op.create_index(op.f('ix_licitacoesPropostas_idLicitacao'), 'licitacoesPropostas', ['idLicitacao'], unique=False)
    op.create_table('proposicoesTemas',
    sa.Column('idProposicao', sa.Integer(), nullable=False),
    sa.Column('idTema', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProposicao'], ['proposicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idTema'], ['temas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idProposicao', 'idTema')
    )
    op.create_table('tramitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProposicao', sa.Integer(), nullable=False),
    sa.Column('dataHora', sa.DateTime(), nullable=True),
    sa.Column('sequencia', sa.Integer(), nullable=True),
    sa.Column('siglaOrgao', sa.String(length=50), nullable=True),
    sa.Column('uriOrgao', sa.Text(), nullable=True),
    sa.Column('uriUltimoRelator', sa.Text(), nullable=True),
    sa.Column('regime', sa.String(length=200), nullable=True),
    sa.Column('descricaoTramitacao', sa.String(length=200), nullable=True),
    sa.Column('codTipoTramitacao', sa.Integer(), nullable=True),
    sa.Column('descricaoSituacao', sa.String(length=150), nullable=True),
    sa.Column('codSituacao', sa.Integer(), nullable=True),
    sa.Column('despacho', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('ambito', sa.String(length=50), nullable=True),
    sa.Column('apreciacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['idProposicao'], ['proposicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tramitacoes_dataHora'), 'tramitacoes', ['dataHora'], unique=False)
    op.create_index(op.f('ix_tramitacoes_idProposicao'), 'tramitacoes', ['idProposicao'], unique=False)
    op.create_index('ix_tramitacoes_prop_seq', 'tramitacoes', ['idProposicao', 'sequencia'], unique=False)
    op.create_table('votacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCamara', sa.String(length=50), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('idProposicao', sa.Integer(), nullable=True),
    sa.Column('idOrgao', sa.Integer(), nullable=True),
    sa.Column('idEvento', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('dataHoraRegistro', sa.DateTime(), nullable=True),
    sa.Column('siglaOrgao', sa.String(length=50), nullable=True),
    sa.Column('uriOrgao', sa.Text(), nullable=True),
    sa.Column('uriEvento', sa.Text(), nullable=True),
    sa.Column('aprovacao', sa.SmallInteger(), nullable=True),
    sa.Column('votosSim', sa.Integer(), nullable=True),
    sa.Column('votosNao', sa.Integer(), nullable=True),
    sa.Column('votosOutros', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipoVotacao', sa.String(length=50), nullable=True),
    sa.Column('votosImportados', sa.Boolean(), nullable=True),
    sa.Column('indexada', sa.Boolean(), nullable=True),
    sa.Column('ultimaAberturaVotacao_dataHoraRegistro', sa.DateTime(), nullable=True),
    sa.Column('ultimaAberturaVotacao_descricao', sa.Text(), nullable=True),
    sa.Column('ultimaApresentacaoProposicao_dataHoraRegistro', sa.DateTime(), nullable=True),
    sa.Column('ultimaApresentacaoProposicao_descricao', sa.Text(), nullable=True),
    sa.Column('ultimaApresentacaoProposicao_idProposicao', sa.Integer(), nullable=True),
    sa.Column('ultimaApresentacaoProposicao_uriProposicao', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idEvento'], ['eventos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idOrgao'], ['orgaos.id'], ),
    sa.ForeignKeyConstraint(['idProposicao'], ['proposicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_votacoes_data_orgao', 'votacoes', ['data', 'siglaOrgao'], unique=False)
    op.create_index(op.f('ix_votacoes_idCamara'), 'votacoes', ['idCamara'], unique=True)
    op.create_index(op.f('ix_votacoes_idOrgao'), 'votacoes', ['idOrgao'], unique=False)
    op.create_index(op.f('ix_votacoes_idProposicao'), 'votacoes', ['idProposicao'], unique=False)
    op.create_table('buscaPopular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idDeputado')
    )
    op.create_index(op.f('ix_buscaPopular_id'), 'buscaPopular', ['id'], unique=False)
    op.create_table('deputadosOcupacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('entidade', sa.Text(), nullable=True),
    sa.Column('entidadeUF', sa.CHAR(length=2), nullable=True),
    sa.Column('entidadePais', sa.Text(), nullable=True),
    sa.Column('anoInicio', sa.Integer(), nullable=True),
    sa.Column('anoFim', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idDeputado', 'titulo', 'entidade', 'entidadeUF', 'entidadePais', 'anoInicio', 'anoFim', name='uq_deputado_ocupacao')
    )
    op.create_index(op.f('ix_deputadosOcupacoes_idDeputado'), 'deputadosOcupacoes', ['idDeputado'], unique=False)
    op.create_table('deputadosProfissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('dataHora', sa.DateTime(), nullable=True),
    sa.Column('codTipoProfissao', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deputadosProfissoes_idDeputado'), 'deputadosProfissoes', ['idDeputado'], unique=False)
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('codDocumento', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('dataDocumento', sa.DateTime(), nullable=True),
    sa.Column('tipoDespesa', sa.Text(), nullable=True),
    sa.Column('numSubCota', sa.Integer(), nullable=True),
    sa.Column('numEspecificacaoSubCota', sa.Integer(), nullable=True),
    sa.Column('codTipoDocumento', sa.Integer(), nullable=True),
    sa.Column('numDocumento', sa.String(length=150), nullable=True),
    sa.Column('urlDocumento', sa.Text(), nullable=True),
    sa.Column('nomeFornecedor', sa.Text(), nullable=True),
    sa.Column('cnpjCpfFornecedor', sa.String(length=20), nullable=True),
    sa.Column('valorDocumento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valorGlosa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valorLiquido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parcela', sa.Integer(), nullable=True),
    sa.Column('codLote', sa.Integer(), nullable=True),
    sa.Column('numRessarcimento', sa.String(length=100), nullable=True),
    sa.Column('txPassageiro', sa.Text(), nullable=True),
    sa.Column('txTrecho', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesas_ano'), 'despesas', ['ano'], unique=False)
    op.create_index(op.f('ix_despesas_cnpjCpfFornecedor'), 'despesas', ['cnpjCpfFornecedor'], unique=False)
    op.create_index(op.f('ix_despesas_codDocumento'), 'despesas', ['codDocumento'], unique=True)
    op.create_index('ix_despesas_dep_ano_mes', 'despesas', ['idDeputado', 'ano', 'mes'], unique=False)
    op.create_index(op.f('ix_despesas_idDeputado'), 'despesas', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_despesas_mes'), 'despesas', ['mes'], unique=False)
    op.create_table('discursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('idEvento', sa.Integer(), nullable=True),
    sa.Column('dataHoraInicio', sa.DateTime(), nullable=False),
    sa.Column('dataHoraFim', sa.DateTime(), nullable=True),
    sa.Column('tipoDiscurso', sa.String(length=100), nullable=True),
    sa.Column('faseEventoTitulo', sa.String(length=255), nullable=True),
    sa.Column('sumario', sa.Text(), nullable=True),
    sa.Column('transcricao', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('urlTexto', sa.Text(), nullable=True),
    sa.Column('urlAudio', sa.Text(), nullable=True),
    sa.Column('urlVideo', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idEvento'], ['eventos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discursos_idDeputado'), 'discursos', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_discursos_idEvento'), 'discursos', ['idEvento'], unique=False)
    op.create_table('eventosPresencaDeputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEvento', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('dataHoraInicio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idEvento'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idEvento', 'idDeputado', name='uq_presenca_evento_deputado')
    )
    op.create_index(op.f('ix_eventosPresencaDeputados_idDeputado'), 'eventosPresencaDeputados', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_eventosPresencaDeputados_idEvento'), 'eventosPresencaDeputados', ['idEvento'], unique=False)
    op.create_table('frentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCamara', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('dataCriacao', sa.Date(), nullable=True),
    sa.Column('idLegislatura', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('idSituacao', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.Text(), nullable=True),
    sa.Column('urlWebsite', sa.Text(), nullable=True),
    sa.Column('urlDocumento', sa.Text(), nullable=True),
    sa.Column('coordenador_id', sa.Integer(), nullable=True),
    sa.Column('coordenador_uri', sa.Text(), nullable=True),
    sa.Column('coordenador_nome', sa.Text(), nullable=True),
    sa.Column('coordenador_siglaPartido', sa.String(length=50), nullable=True),
    sa.Column('coordenador_uriPartido', sa.Text(), nullable=True),
    sa.Column('coordenador_siglaUf', sa.CHAR(length=2), nullable=True),
    sa.Column('coordenador_idLegislatura', sa.Integer(), nullable=True),
    sa.Column('coordenador_urlFoto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coordenador_id'], ['deputados.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idLegislatura'], ['legislaturas.idLegislatura'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_frentes_idCamara'), 'frentes', ['idCamara'], unique=True)
    op.create_table('gruposMembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idGrupo', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=True),
    sa.Column('idLegislatura', sa.Integer(), nullable=True),
    sa.Column('ordemEntrada', sa.Integer(), nullable=True),
    sa.Column('dataInicio', sa.DateTime(), nullable=True),
    sa.Column('dataFim', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idGrupo'], ['grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idGrupo', 'idDeputado', name='uq_grupo_membro')
    )
    op.create_index(op.f('ix_gruposMembros_idDeputado'), 'gruposMembros', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_gruposMembros_idGrupo'), 'gruposMembros', ['idGrupo'], unique=False)
    op.create_table('legislaturasMesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idLegislatura', sa.Integer(), nullable=False),
    sa.Column('idOrgao', sa.Integer(), nullable=True),
    sa.Column('uriOrgao', sa.Text(), nullable=True),
    sa.Column('siglaOrgao', sa.String(length=50), nullable=True),
    sa.Column('nomeOrgao', sa.String(length=200), nullable=True),
    sa.Column('idDeputado', sa.Integer(), nullable=True),
    sa.Column('uriDeputado', sa.Text(), nullable=True),
    sa.Column('nomeDeputado', sa.String(length=200), nullable=True),
    sa.Column('siglaPartido', sa.String(length=50), nullable=True),
    sa.Column('siglaUF', sa.CHAR(length=2), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('dataInicio', sa.DateTime(), nullable=True),
    sa.Column('dataFim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.idCamara'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idLegislatura'], ['legislaturas.idLegislatura'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idOrgao'], ['orgaos.idCamara'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idLegislatura', 'idDeputado', 'cargo', 'dataInicio', name='uq_mesa_leg_dep_cargo_data')
    )
    op.create_index(op.f('ix_legislaturasMesas_idDeputado'), 'legislaturasMesas', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_legislaturasMesas_idLegislatura'), 'legislaturasMesas', ['idLegislatura'], unique=False)
    op.create_index(op.f('ix_legislaturasMesas_idOrgao'), 'legislaturasMesas', ['idOrgao'], unique=False)
    op.create_table('orgaosDeputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idOrgao', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=True),
    sa.Column('nomePublicacaoOrgao', sa.Text(), nullable=True),
    sa.Column('uriDeputado', sa.Text(), nullable=True),
    sa.Column('nomeDeputado', sa.String(length=200), nullable=True),
    sa.Column('siglaPartido', sa.String(length=50), nullable=True),
    sa.Column('siglaUF', sa.CHAR(length=2), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('codTitulo', sa.Integer(), nullable=True),
    sa.Column('dataInicio', sa.Date(), nullable=True),
    sa.Column('dataFim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idOrgao'], ['orgaos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idOrgao', 'idDeputado', name='uq_orgaodeputado')
    )
    op.create_index(op.f('ix_orgaosDeputados_idDeputado'), 'orgaosDeputados', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_orgaosDeputados_idOrgao'), 'orgaosDeputados', ['idOrgao'], unique=False)
    op.create_table('partidosLideres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPartido', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=True),
    sa.Column('codTitulo', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('dataInicio', sa.Date(), nullable=True),
    sa.Column('dataFim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idPartido'], ['partidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidosLideres_idDeputado'), 'partidosLideres', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_partidosLideres_idPartido'), 'partidosLideres', ['idPartido'], unique=False)
    op.create_table('partidosMembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPartido', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=True),
    sa.Column('dataInicio', sa.Date(), nullable=True),
    sa.Column('dataFim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idPartido'], ['partidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idPartido', 'idDeputado', name='uq_partido_membro')
    )
    op.create_index(op.f('ix_partidosMembros_idDeputado'), 'partidosMembros', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_partidosMembros_idPartido'), 'partidosMembros', ['idPartido'], unique=False)
    op.create_table('proposicoesAutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProposicao', sa.Integer(), nullable=False),
    sa.Column('idDeputadoAutor', sa.Integer(), nullable=True),
    sa.Column('uriAutor', sa.Text(), nullable=True),
    sa.Column('codTipoAutor', sa.Integer(), nullable=True),
    sa.Column('tipoAutor', sa.String(length=50), nullable=True),
    sa.Column('nomeAutor', sa.Text(), nullable=False),
    sa.Column('siglaPartidoAutor', sa.String(length=50), nullable=True),
    sa.Column('uriPartidoAutor', sa.Text(), nullable=True),
    sa.Column('siglaUFAutor', sa.CHAR(length=2), nullable=True),
    sa.Column('ordemAssinatura', sa.Integer(), nullable=True),
    sa.Column('proponente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputadoAutor'], ['deputados.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idProposicao'], ['proposicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idProposicao', 'idDeputadoAutor', 'nomeAutor', name='uq_autor_proposicao', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_proposicoesAutores_idDeputadoAutor'), 'proposicoesAutores', ['idDeputadoAutor'], unique=False)
    op.create_index(op.f('ix_proposicoesAutores_idProposicao'), 'proposicoesAutores', ['idProposicao'], unique=False)
    op.create_table('verbasGabinete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=True),
    sa.Column('idCamara', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('valorDisponivel', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valorGasto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verbasGabinete_ano'), 'verbasGabinete', ['ano'], unique=False)
    op.create_index(op.f('ix_verbasGabinete_id'), 'verbasGabinete', ['id'], unique=False)
    op.create_index(op.f('ix_verbasGabinete_idCamara'), 'verbasGabinete', ['idCamara'], unique=False)
    op.create_index(op.f('ix_verbasGabinete_idDeputado'), 'verbasGabinete', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_verbasGabinete_mes'), 'verbasGabinete', ['mes'], unique=False)
    op.create_table('votacoesObjetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idVotacao', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('proposicao_id', sa.Integer(), nullable=True),
    sa.Column('proposicao_uri', sa.Text(), nullable=True),
    sa.Column('proposicao_ementa', sa.Text(), nullable=True),
    sa.Column('proposicao_codTipo', sa.Integer(), nullable=True),
    sa.Column('proposicao_siglaTipo', sa.String(length=50), nullable=True),
    sa.Column('proposicao_numero', sa.Integer(), nullable=True),
    sa.Column('proposicao_ano', sa.Integer(), nullable=True),
    sa.Column('proposicao_titulo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['idVotacao'], ['votacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votacoesObjetos_idVotacao'), 'votacoesObjetos', ['idVotacao'], unique=False)
    op.create_index(op.f('ix_votacoesObjetos_proposicao_id'), 'votacoesObjetos', ['proposicao_id'], unique=False)
    op.create_table('votacoesOrientacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idVotacao', sa.Integer(), nullable=False),
    sa.Column('siglaOrgao', sa.String(length=50), nullable=True),
    sa.Column('siglaBancada', sa.String(length=50), nullable=True),
    sa.Column('uriBancada', sa.Text(), nullable=True),
    sa.Column('orientacao', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['idVotacao'], ['votacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votacoesOrientacoes_idVotacao'), 'votacoesOrientacoes', ['idVotacao'], unique=False)
    op.create_table('votacoesVotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idVotacao', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=False),
    sa.Column('dataHoraVoto', sa.DateTime(), nullable=True),
    sa.Column('voto', sa.String(length=30), nullable=True),
    sa.Column('siglaPartido', sa.String(length=50), nullable=True),
    sa.Column('uriPartido', sa.Text(), nullable=True),
    sa.Column('siglaUF', sa.CHAR(length=2), nullable=True),
    sa.Column('idLegislatura', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idVotacao'], ['votacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idVotacao', 'idDeputado', name='uq_voto_votacao_deputado')
    )
    op.create_index(op.f('ix_votacoesVotos_idDeputado'), 'votacoesVotos', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_votacoesVotos_idVotacao'), 'votacoesVotos', ['idVotacao'], unique=False)
    op.create_table('frentesDeputados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idFrente', sa.Integer(), nullable=False),
    sa.Column('idDeputado', sa.Integer(), nullable=True),
    sa.Column('uriDeputado', sa.Text(), nullable=True),
    sa.Column('uriPartido', sa.Text(), nullable=True),
    sa.Column('nomeDeputado', sa.String(length=200), nullable=True),
    sa.Column('siglaUf', sa.CHAR(length=2), nullable=True),
    sa.Column('idLegislatura', sa.Integer(), nullable=True),
    sa.Column('urlFoto', sa.Text(), nullable=True),
    sa.Column('codTitulo', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('dataInicio', sa.Date(), nullable=True),
    sa.Column('dataFim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idDeputado'], ['deputados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idFrente'], ['frentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idFrente', 'idDeputado', name='uq_frente_deputado')
    )
    op.create_index(op.f('ix_frentesDeputados_idDeputado'), 'frentesDeputados', ['idDeputado'], unique=False)
    op.create_index(op.f('ix_frentesDeputados_idFrente'), 'frentesDeputados', ['idFrente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frentesDeputados_idFrente'), table_name='frentesDeputados')
    op.drop_index(op.f('ix_frentesDeputados_idDeputado'), table_name='frentesDeputados')
    op.drop_table('frentesDeputados')
    op.drop_index(op.f('ix_votacoesVotos_idVotacao'), table_name='votacoesVotos')
    op.drop_index(op.f('ix_votacoesVotos_idDeputado'), table_name='votacoesVotos')
    op.drop_table('votacoesVotos')
    op.drop_index(op.f('ix_votacoesOrientacoes_idVotacao'), table_name='votacoesOrientacoes')
    op.drop_table('votacoesOrientacoes')
    op.drop_index(op.f('ix_votacoesObjetos_proposicao_id'), table_name='votacoesObjetos')
    op.drop_index(op.f('ix_votacoesObjetos_idVotacao'), table_name='votacoesObjetos')
    op.drop_table('votacoesObjetos')
    op.drop_index(op.f('ix_verbasGabinete_mes'), table_name='verbasGabinete')
    op.drop_index(op.f('ix_verbasGabinete_idDeputado'), table_name='verbasGabinete')
    op.drop_index(op.f('ix_verbasGabinete_idCamara'), table_name='verbasGabinete')
    op.drop_index(op.f('ix_verbasGabinete_id'), table_name='verbasGabinete')
    op.drop_index(op.f('ix_verbasGabinete_ano'), table_name='verbasGabinete')
    op.drop_table('verbasGabinete')
    op.drop_index(op.f('ix_proposicoesAutores_idProposicao'), table_name='proposicoesAutores')
    op.drop_index(op.f('ix_proposicoesAutores_idDeputadoAutor'), table_name='proposicoesAutores')
    op.drop_table('proposicoesAutores')
    op.drop_index(op.f('ix_partidosMembros_idPartido'), table_name='partidosMembros')
    op.drop_index(op.f('ix_partidosMembros_idDeputado'), table_name='partidosMembros')
    op.drop_table('partidosMembros')
    op.drop_index(op.f('ix_partidosLideres_idPartido'), table_name='partidosLideres')
    op.drop_index(op.f('ix_partidosLideres_idDeputado'), table_name='partidosLideres')
    op.drop_table('partidosLideres')
    op.drop_index(op.f('ix_orgaosDeputados_idOrgao'), table_name='orgaosDeputados')
    op.drop_index(op.f('ix_orgaosDeputados_idDeputado'), table_name='orgaosDeputados')
    op.drop_table('orgaosDeputados')
    op.drop_index(op.f('ix_legislaturasMesas_idOrgao'), table_name='legislaturasMesas')
    op.drop_index(op.f('ix_legislaturasMesas_idLegislatura'), table_name='legislaturasMesas')
    op.drop_index(op.f('ix_legislaturasMesas_idDeputado'), table_name='legislaturasMesas')
    op.drop_table('legislaturasMesas')
    op.drop_index(op.f('ix_gruposMembros_idGrupo'), table_name='gruposMembros')
    op.drop_index(op.f('ix_gruposMembros_idDeputado'), table_name='gruposMembros')
    op.drop_table('gruposMembros')
    op.drop_index(op.f('ix_frentes_idCamara'), table_name='frentes')
    op.drop_table('frentes')
    op.drop_index(op.f('ix_eventosPresencaDeputados_idEvento'), table_name='eventosPresencaDeputados')
    op.drop_index(op.f('ix_eventosPresencaDeputados_idDeputado'), table_name='eventosPresencaDeputados')
    op.drop_table('eventosPresencaDeputados')
    op.drop_index(op.f('ix_discursos_idEvento'), table_name='discursos')
    op.drop_index(op.f('ix_discursos_idDeputado'), table_name='discursos')
    op.drop_table('discursos')
    op.drop_index(op.f('ix_despesas_mes'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_idDeputado'), table_name='despesas')
    op.drop_index('ix_despesas_dep_ano_mes', table_name='despesas')
    op.drop_index(op.f('ix_despesas_codDocumento'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_cnpjCpfFornecedor'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_ano'), table_name='despesas')
    op.drop_table('despesas')
    op.drop_index(op.f('ix_deputadosProfissoes_idDeputado'), table_name='deputadosProfissoes')
    op.drop_table('deputadosProfissoes')
    op.drop_index(op.f('ix_deputadosOcupacoes_idDeputado'), table_name='deputadosOcupacoes')
    op.drop_table('deputadosOcupacoes')
    op.drop_index(op.f('ix_buscaPopular_id'), table_name='buscaPopular')
    op.drop_table('buscaPopular')
    op.drop_index(op.f('ix_votacoes_idProposicao'), table_name='votacoes')
    op.drop_index(op.f('ix_votacoes_idOrgao'), table_name='votacoes')
    op.drop_index(op.f('ix_votacoes_idCamara'), table_name='votacoes')
    op.drop_index('ix_votacoes_data_orgao', table_name='votacoes')
    op.drop_table('votacoes')
    op.drop_index('ix_tramitacoes_prop_seq', table_name='tramitacoes')
    op.drop_index(op.f('ix_tramitacoes_idProposicao'), table_name='tramitacoes')
    op.drop_index(op.f('ix_tramitacoes_dataHora'), table_name='tramitacoes')
    op.drop_table('tramitacoes')
    op.drop_table('proposicoesTemas')
    op.drop_index(op.f('ix_licitacoesPropostas_idLicitacao'), table_name='licitacoesPropostas')
    op.drop_index(op.f('ix_licitacoesPropostas_fornecedorCpfCnpj'), table_name='licitacoesPropostas')
    op.drop_table('licitacoesPropostas')
    op.drop_index(op.f('ix_licitacoesPedidos_idLicitacao'), table_name='licitacoesPedidos')
    op.drop_index(op.f('ix_licitacoesPedidos_ano'), table_name='licitacoesPedidos')
    op.drop_table('licitacoesPedidos')
    op.drop_index(op.f('ix_licitacoesItens_idLicitacao'), table_name='licitacoesItens')
    op.drop_index(op.f('ix_licitacoesItens_fornecedorCpfCnpj'), table_name='licitacoesItens')
    op.drop_table('licitacoesItens')
    op.drop_index(op.f('ix_licitacoesContratos_idLicitacao'), table_name='licitacoesContratos')
    op.drop_index(op.f('ix_licitacoesContratos_fornecedorCpfCnpj'), table_name='licitacoesContratos')
    op.drop_table('licitacoesContratos')
    op.drop_index(op.f('ix_gruposHistorico_idGrupo'), table_name='gruposHistorico')
    op.drop_table('gruposHistorico')
    op.drop_index(op.f('ix_eventosRequerimentos_idEvento'), table_name='eventosRequerimentos')
    op.drop_table('eventosRequerimentos')
    op.drop_table('eventosOrgaos')
    op.drop_index(op.f('ix_deputados_slug'), table_name='deputados')
    op.drop_index(op.f('ix_deputados_siglaUF'), table_name='deputados')
    op.drop_index(op.f('ix_deputados_siglaPartido'), table_name='deputados')
    op.drop_index(op.f('ix_deputados_nome'), table_name='deputados')
    op.drop_index(op.f('ix_deputados_idLegislaturaFinal'), table_name='deputados')
    op.drop_index(op.f('ix_deputados_idCamara'), table_name='deputados')
    op.drop_table('deputados')
    op.drop_index(op.f('ix_temas_tema'), table_name='temas')
    op.drop_index(op.f('ix_temas_codTema'), table_name='temas')
    op.drop_table('temas')
    op.drop_index(op.f('ix_tecadTermos_termo'), table_name='tecadTermos')
    op.drop_index(op.f('ix_tecadTermos_codTermo'), table_name='tecadTermos')
    op.drop_table('tecadTermos')
    op.drop_index(op.f('ix_tecadCategorias_codSubCategoria'), table_name='tecadCategorias')
    op.drop_index(op.f('ix_tecadCategorias_codCategoria'), table_name='tecadCategorias')
    op.drop_table('tecadCategorias')
    op.drop_index(op.f('ix_proposicoes_uri'), table_name='proposicoes')
    op.drop_index('ix_proposicoes_tipo_ano', table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_siglaTipo'), table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_numero'), table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_idCamara'), table_name='proposicoes')
    op.drop_index(op.f('ix_proposicoes_ano'), table_name='proposicoes')
    op.drop_table('proposicoes')
    op.drop_index(op.f('ix_partidos_sigla'), table_name='partidos')
    op.drop_index(op.f('ix_partidos_idCamara'), table_name='partidos')
    op.drop_table('partidos')
    op.drop_index(op.f('ix_orgaos_sigla'), table_name='orgaos')
    op.drop_index(op.f('ix_orgaos_idCamara'), table_name='orgaos')
    op.drop_table('orgaos')
    op.drop_index(op.f('ix_licitacoes_idLicitacao'), table_name='licitacoes')
    op.drop_index('ix_licitacoes_ano_sit', table_name='licitacoes')
    op.drop_index(op.f('ix_licitacoes_ano'), table_name='licitacoes')
    op.drop_table('licitacoes')
    op.drop_index(op.f('ix_legislaturas_idLegislatura'), table_name='legislaturas')
    op.drop_table('legislaturas')
    op.drop_index(op.f('ix_grupos_idCamara'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_ativo'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_funcionarios_ponto'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_nome'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_eventos_idCamara'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_dataHoraInicio'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
