"""aumenta_tamanho_titulo

Revision ID: f3f0e8223578
Revises: c1a2b3d4e5f6
Create Date: 2026-09-11 15:02:41.962477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f3f0e8223578"
down_revision: Union[str, Sequence[str], None] = "c1a2b3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_deputado_perfil_vetor_discursos_hnsw",
        "deputadoPerfilVetorial",
        ["vetorDiscursos"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"vetorDiscursos": "vector_cosine_ops"},
    )
    op.create_unique_constraint(
        "uq_discursos_dep_inicio_tipo",
        "discursos",
        ["idDeputado", "dataHoraInicio", "tipoDiscurso"],
    )
    op.alter_column(
        "frentesDeputados",
        "titulo",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "partidosLideres",
        "titulo",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("temasAtuacao_slug_key"), "temasAtuacao", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("temasAtuacao_slug_key"),
        "temasAtuacao",
        ["slug"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "partidosLideres",
        "titulo",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "frentesDeputados",
        "titulo",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_constraint("uq_discursos_dep_inicio_tipo", "discursos", type_="unique")
    op.drop_index(
        "ix_deputado_perfil_vetor_discursos_hnsw",
        table_name="deputadoPerfilVetorial",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"vetorDiscursos": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###
