name: CI - Testes e Segurança

on:
  push:
    branches: [ main, novaDB ] # Roda nas suas branches principais
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Ganhe velocidade com cache de libs

      - name: Sincronizar dependências
        run: uv sync

      #- name: Instalar Python
      # run: uv python install 3.12

      - name: Rodar Linter (Ruff)
        run: uv run ruff check .

      - name: Security Scan (Bandit)
        # Como você é de SegInfo, isso aqui é obrigatório no seu currículo
        run: uv run bandit -r . -x ./tests -c ./tests/bandit_conf.yml

      - name: Rodar Testes (Pytest)
        run: uv run pytest
