name: CI - Testes e Segurança

on:
  push:
    branches: [ main, test-env] # Roda nas suas branches principais
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: quemvota
          POSTGRES_PASSWORD: quemvota
          POSTGRES_DB: quemvota_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      valkey:
        image: valkey/valkey:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Ganhe velocidade com cache de libs

      - name: Sincronizar dependências
        run: uv sync

      - name: Rodar migrations
        env:
          DATABASE_URL: postgresql+asyncpg://quemvota:quemvota@localhost/quemvota_test
        run: uv run alembic upgrade head
      #- name: Instalar Python
      # run: uv python install 3.12

      - name: Rodar Linter (Ruff)
        run: uv run ruff check .

      - name: Security Scan (Bandit)
        # Como você é de SegInfo, isso aqui é obrigatório no seu currículo
        run: uv run bandit -r . -x ./tests -c ./tests/bandit_conf.yml

      - name: Rodar Testes (Pytest)
        run: uv run pytest
