name: Deploy model to VPS

on:
  push:
    branches: [ main ]

jobs:  
  deploy:
      needs: lint-and-test # only deploy if tests pass
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
        - name: Deploy via SSH
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.AWS_HOST }}
            username: ${{ secrets.AWS_USER }}
            key: ${{ secrets.AWS_SSH_KEY }}
            script: |
              cd /opt/quemVota/deploy
              git pull origin main
              docker compose up --build -d
