name: Deploy model to VPS

on:
  push:
    branches: [ main ]

jobs:  
  call-ci:
    uses: ./.github/workflows/ci.yml

  deploy:
      needs: call-ci # only deploy if tests pass
      runs-on: ubuntu-latest
      steps:
        - name: Deploy via SSH
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.AWS_HOST }}
            username: ${{ secrets.AWS_USER }}
            key: ${{ secrets.AWS_SSH_KEY }}
            script: sudo bash /opt/quemVota/deploy/deploy.sh
